//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Labels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absoluto.
        /// </summary>
        internal static string Absoluto {
            get {
                return ResourceManager.GetString("Absoluto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic &amp; Professional Certificates.
        /// </summary>
        internal static string AcademicCertificates {
            get {
                return ResourceManager.GetString("AcademicCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Education.
        /// </summary>
        internal static string AcademicEducation {
            get {
                return ResourceManager.GetString("AcademicEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Brannch.
        /// </summary>
        internal static string AddBrannch {
            get {
                return ResourceManager.GetString("AddBrannch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Custody.
        /// </summary>
        internal static string AddCustody {
            get {
                return ResourceManager.GetString("AddCustody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Department.
        /// </summary>
        internal static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added By.
        /// </summary>
        internal static string AddedBy {
            get {
                return ResourceManager.GetString("AddedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Job.
        /// </summary>
        internal static string AddJob {
            get {
                return ResourceManager.GetString("AddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Management.
        /// </summary>
        internal static string AddManagement {
            get {
                return ResourceManager.GetString("AddManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add MaterialsConsumption.
        /// </summary>
        internal static string AddMaterialsConsumption {
            get {
                return ResourceManager.GetString("AddMaterialsConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Penalties.
        /// </summary>
        internal static string AddPenalties {
            get {
                return ResourceManager.GetString("AddPenalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Period.
        /// </summary>
        internal static string AddPeriod {
            get {
                return ResourceManager.GetString("AddPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Personal Permission.
        /// </summary>
        internal static string AddPersonalPermission {
            get {
                return ResourceManager.GetString("AddPersonalPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Rewards or Penalties.
        /// </summary>
        internal static string AddRewardsOrPenalties {
            get {
                return ResourceManager.GetString("AddRewardsOrPenalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Salary Increase.
        /// </summary>
        internal static string AddSalaryIncrease {
            get {
                return ResourceManager.GetString("AddSalaryIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddTask.
        /// </summary>
        internal static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddTraining.
        /// </summary>
        internal static string AddTraining {
            get {
                return ResourceManager.GetString("AddTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vacation.
        /// </summary>
        internal static string AddVacation {
            get {
                return ResourceManager.GetString("AddVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Working Permission.
        /// </summary>
        internal static string AddWorkingPermission {
            get {
                return ResourceManager.GetString("AddWorkingPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisors.
        /// </summary>
        internal static string Advisors {
            get {
                return ResourceManager.GetString("Advisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual.
        /// </summary>
        internal static string Annual {
            get {
                return ResourceManager.GetString("Annual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        internal static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance and Vacations.
        /// </summary>
        internal static string AttendanceAndVacations {
            get {
                return ResourceManager.GetString("AttendanceAndVacations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        internal static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Type.
        /// </summary>
        internal static string Blood {
            get {
                return ResourceManager.GetString("Blood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string bod {
            get {
                return ResourceManager.GetString("bod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        internal static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Manager.
        /// </summary>
        internal static string BranchManager {
            get {
                return ResourceManager.GetString("BranchManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancle.
        /// </summary>
        internal static string Cancle {
            get {
                return ResourceManager.GetString("Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        internal static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Number.
        /// </summary>
        internal static string CarNumber {
            get {
                return ResourceManager.GetString("CarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casado.
        /// </summary>
        internal static string Casado {
            get {
                return ResourceManager.GetString("Casado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO.
        /// </summary>
        internal static string CEO {
            get {
                return ResourceManager.GetString("CEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        internal static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate 1.
        /// </summary>
        internal static string Certificate1 {
            get {
                return ResourceManager.GetString("Certificate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate 2.
        /// </summary>
        internal static string Certificate2 {
            get {
                return ResourceManager.GetString("Certificate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate3.
        /// </summary>
        internal static string Certificate3 {
            get {
                return ResourceManager.GetString("Certificate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil No.
        /// </summary>
        internal static string CivilNo {
            get {
                return ResourceManager.GetString("CivilNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientRelation.
        /// </summary>
        internal static string ClientRelation {
            get {
                return ResourceManager.GetString("ClientRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        internal static string Communication {
            get {
                return ResourceManager.GetString("Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information.
        /// </summary>
        internal static string CompanyInfo {
            get {
                return ResourceManager.GetString("CompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company List.
        /// </summary>
        internal static string CompanyList {
            get {
                return ResourceManager.GetString("CompanyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Arabic.
        /// </summary>
        internal static string CompanyListAr {
            get {
                return ResourceManager.GetString("CompanyListAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in English.
        /// </summary>
        internal static string CompanyListEn {
            get {
                return ResourceManager.GetString("CompanyListEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Owner in arabic.
        /// </summary>
        internal static string CompanyOwnerAr {
            get {
                return ResourceManager.GetString("CompanyOwnerAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Owner in english.
        /// </summary>
        internal static string CompanyOwnerEn {
            get {
                return ResourceManager.GetString("CompanyOwnerEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confronts problems Directly.
        /// </summary>
        internal static string ConfrontsProblems {
            get {
                return ResourceManager.GetString("ConfrontsProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooperation / Relationship Building.
        /// </summary>
        internal static string Cooperation {
            get {
                return ResourceManager.GetString("Cooperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creativity.
        /// </summary>
        internal static string Creativity {
            get {
                return ResourceManager.GetString("Creativity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Salary.
        /// </summary>
        internal static string CurrentSalary {
            get {
                return ResourceManager.GetString("CurrentSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custody.
        /// </summary>
        internal static string Custody {
            get {
                return ResourceManager.GetString("Custody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies Customer Needs.
        /// </summary>
        internal static string CustomerNeeds {
            get {
                return ResourceManager.GetString("CustomerNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        internal static string DeleteSuccessfully {
            get {
                return ResourceManager.GetString("DeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        internal static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Manager.
        /// </summary>
        internal static string DeptManager {
            get {
                return ResourceManager.GetString("DeptManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Manager Assestant.
        /// </summary>
        internal static string DeptManagerAssestant {
            get {
                return ResourceManager.GetString("DeptManagerAssestant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Supervisor.
        /// </summary>
        internal static string DirectSupervisor {
            get {
                return ResourceManager.GetString("DirectSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Mannerism.
        /// </summary>
        internal static string EmployeeMannerism {
            get {
                return ResourceManager.GetString("EmployeeMannerism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Attendance.
        /// </summary>
        internal static string EmployeesAttendance {
            get {
                return ResourceManager.GetString("EmployeesAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Information.
        /// </summary>
        internal static string EmployeesInfo {
            get {
                return ResourceManager.GetString("EmployeesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Penalties.
        /// </summary>
        internal static string EmployeesPenalties {
            get {
                return ResourceManager.GetString("EmployeesPenalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Penalties.
        /// </summary>
        internal static string EmpPenalties {
            get {
                return ResourceManager.GetString("EmpPenalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Date.
        /// </summary>
        internal static string EvaluationDate {
            get {
                return ResourceManager.GetString("EvaluationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above Expectations (Excellent).
        /// </summary>
        internal static string Excellent {
            get {
                return ResourceManager.GetString("Excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive Procedures.
        /// </summary>
        internal static string ExecutiveProcedures {
            get {
                return ResourceManager.GetString("ExecutiveProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience 1.
        /// </summary>
        internal static string Experience1 {
            get {
                return ResourceManager.GetString("Experience1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience 2.
        /// </summary>
        internal static string Experience2 {
            get {
                return ResourceManager.GetString("Experience2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience 3.
        /// </summary>
        internal static string Experience3 {
            get {
                return ResourceManager.GetString("Experience3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Passports.
        /// </summary>
        internal static string ExpiredPassports {
            get {
                return ResourceManager.GetString("ExpiredPassports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Expectations (Fair).
        /// </summary>
        internal static string Fair {
            get {
                return ResourceManager.GetString("Fair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Manager.
        /// </summary>
        internal static string FinancialManager {
            get {
                return ResourceManager.GetString("FinancialManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Director.
        /// </summary>
        internal static string GeneralDirector {
            get {
                return ResourceManager.GetString("GeneralDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meets Expectations (Good).
        /// </summary>
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantor.
        /// </summary>
        internal static string Guarantor {
            get {
                return ResourceManager.GetString("Guarantor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle strssful situations.
        /// </summary>
        internal static string HandleStressful {
            get {
                return ResourceManager.GetString("HandleStressful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head of Department.
        /// </summary>
        internal static string HeadOfDepartment {
            get {
                return ResourceManager.GetString("HeadOfDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment Date.
        /// </summary>
        internal static string HiringDate {
            get {
                return ResourceManager.GetString("HiringDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Bills.
        /// </summary>
        internal static string HourlyBills {
            get {
                return ResourceManager.GetString("HourlyBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Permission.
        /// </summary>
        internal static string HourlyPermission {
            get {
                return ResourceManager.GetString("HourlyPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Manager.
        /// </summary>
        internal static string HRManager {
            get {
                return ResourceManager.GetString("HRManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resource.
        /// </summary>
        internal static string HumanResource {
            get {
                return ResourceManager.GetString("HumanResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiative.
        /// </summary>
        internal static string Initiative {
            get {
                return ResourceManager.GetString("Initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description.
        /// </summary>
        internal static string JobDescription {
            get {
                return ResourceManager.GetString("JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Details.
        /// </summary>
        internal static string JobDetails {
            get {
                return ResourceManager.GetString("JobDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Knowledge.
        /// </summary>
        internal static string JobKnowledge {
            get {
                return ResourceManager.GetString("JobKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string JobsTitle {
            get {
                return ResourceManager.GetString("JobsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        internal static string Legal {
            get {
                return ResourceManager.GetString("Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening Skills.
        /// </summary>
        internal static string ListeningSkills {
            get {
                return ResourceManager.GetString("ListeningSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significantly Below Expectation (Low).
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Manager.
        /// </summary>
        internal static string ManagementManager {
            get {
                return ResourceManager.GetString("ManagementManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to managements.
        /// </summary>
        internal static string Managements {
            get {
                return ResourceManager.GetString("Managements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing Director in arabic.
        /// </summary>
        internal static string ManagingDirectorAr {
            get {
                return ResourceManager.GetString("ManagingDirectorAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing Director in english.
        /// </summary>
        internal static string ManagingDirectorEn {
            get {
                return ResourceManager.GetString("ManagingDirectorEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        internal static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials Consumption.
        /// </summary>
        internal static string MaterialsConsumption {
            get {
                return ResourceManager.GetString("MaterialsConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Deadlines.
        /// </summary>
        internal static string MeetingDeadlines {
            get {
                return ResourceManager.GetString("MeetingDeadlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in Arabic.
        /// </summary>
        internal static string NameAR {
            get {
                return ResourceManager.GetString("NameAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in English.
        /// </summary>
        internal static string NameEN {
            get {
                return ResourceManager.GetString("NameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Employee.
        /// </summary>
        internal static string NewEmployee {
            get {
                return ResourceManager.GetString("NewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Event.
        /// </summary>
        internal static string NewEvent {
            get {
                return ResourceManager.GetString("NewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offices.
        /// </summary>
        internal static string Offices {
            get {
                return ResourceManager.GetString("Offices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commits to the mission, vision and objectives of the organization..
        /// </summary>
        internal static string OrganizationVision {
            get {
                return ResourceManager.GetString("OrganizationVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize Idea.
        /// </summary>
        internal static string OrganizeIdea {
            get {
                return ResourceManager.GetString("OrganizeIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over All Progress.
        /// </summary>
        internal static string OverAllProgress {
            get {
                return ResourceManager.GetString("OverAllProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport End Date.
        /// </summary>
        internal static string PassportEnddate {
            get {
                return ResourceManager.GetString("PassportEnddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport And residence .
        /// </summary>
        internal static string PassportInfo {
            get {
                return ResourceManager.GetString("PassportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passport No.
        /// </summary>
        internal static string passportNo {
            get {
                return ResourceManager.GetString("passportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Start Date.
        /// </summary>
        internal static string PassportStartdate {
            get {
                return ResourceManager.GetString("PassportStartdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalties and Company List.
        /// </summary>
        internal static string PenalitiesAndCompanyList {
            get {
                return ResourceManager.GetString("PenalitiesAndCompanyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalties.
        /// </summary>
        internal static string Penalties {
            get {
                return ResourceManager.GetString("Penalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty.
        /// </summary>
        internal static string Penalty {
            get {
                return ResourceManager.GetString("Penalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance(Quality of work ).
        /// </summary>
        internal static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Indicator.
        /// </summary>
        internal static string PerformanceIndicator {
            get {
                return ResourceManager.GetString("PerformanceIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        internal static string Periods {
            get {
                return ResourceManager.GetString("Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Permission.
        /// </summary>
        internal static string PersonalPermission {
            get {
                return ResourceManager.GetString("PersonalPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Permissions.
        /// </summary>
        internal static string PersonalPermissions {
            get {
                return ResourceManager.GetString("PersonalPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Manager in arabic.
        /// </summary>
        internal static string PersonnelManagerAr {
            get {
                return ResourceManager.GetString("PersonnelManagerAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Manager in english.
        /// </summary>
        internal static string PersonnelManagerEn {
            get {
                return ResourceManager.GetString("PersonnelManagerEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical.
        /// </summary>
        internal static string Physical {
            get {
                return ResourceManager.GetString("Physical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Employment.
        /// </summary>
        internal static string PreviousEmployment {
            get {
                return ResourceManager.GetString("PreviousEmployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Experience.
        /// </summary>
        internal static string PreviousExperience {
            get {
                return ResourceManager.GetString("PreviousExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivity.
        /// </summary>
        internal static string Productivity {
            get {
                return ResourceManager.GetString("Productivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuality.
        /// </summary>
        internal static string Punctuality {
            get {
                return ResourceManager.GetString("Punctuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        internal static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        internal static string Recovery {
            get {
                return ResourceManager.GetString("Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated Every.
        /// </summary>
        internal static string RepeatedEvery {
            get {
                return ResourceManager.GetString("RepeatedEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respond resourcefully, flexibly, and positively.
        /// </summary>
        internal static string RespondResourcefully {
            get {
                return ResourceManager.GetString("RespondResourcefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer.
        /// </summary>
        internal static string Reviewer {
            get {
                return ResourceManager.GetString("Reviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward.
        /// </summary>
        internal static string Reward {
            get {
                return ResourceManager.GetString("Reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewards and Penalties.
        /// </summary>
        internal static string RewardsAndPenalties {
            get {
                return ResourceManager.GetString("RewardsAndPenalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Increase.
        /// </summary>
        internal static string SalaryIncrease {
            get {
                return ResourceManager.GetString("SalaryIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        internal static string SaveSuccessfully {
            get {
                return ResourceManager.GetString("SaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Here....
        /// </summary>
        internal static string SelectHere {
            get {
                return ResourceManager.GetString("SelectHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Num.
        /// </summary>
        internal static string SequenceNum {
            get {
                return ResourceManager.GetString("SequenceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soltero.
        /// </summary>
        internal static string Soltero {
            get {
                return ResourceManager.GetString("Soltero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Evaluation.
        /// </summary>
        internal static string StaffEvaluation {
            get {
                return ResourceManager.GetString("StaffEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay focused on helping customer.
        /// </summary>
        internal static string StayFocused {
            get {
                return ResourceManager.GetString("StayFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategic Thinking.
        /// </summary>
        internal static string StrategicThinking {
            get {
                return ResourceManager.GetString("StrategicThinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        internal static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string TextDirection {
            get {
                return ResourceManager.GetString("TextDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TheName {
            get {
                return ResourceManager.GetString("TheName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        internal static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainings.
        /// </summary>
        internal static string Trainings {
            get {
                return ResourceManager.GetString("Trainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unified Number.
        /// </summary>
        internal static string UnifiedNumber {
            get {
                return ResourceManager.GetString("UnifiedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exist.
        /// </summary>
        internal static string UserNameExist {
            get {
                return ResourceManager.GetString("UserNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Information.
        /// </summary>
        internal static string UsersInfo {
            get {
                return ResourceManager.GetString("UsersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation.
        /// </summary>
        internal static string Vacation {
            get {
                return ResourceManager.GetString("Vacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation Report.
        /// </summary>
        internal static string VacationReport {
            get {
                return ResourceManager.GetString("VacationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacations.
        /// </summary>
        internal static string Vacations {
            get {
                return ResourceManager.GetString("Vacations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacations Balance.
        /// </summary>
        internal static string VacationsBalance {
            get {
                return ResourceManager.GetString("VacationsBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacaition Approval.
        /// </summary>
        internal static string VaccaitionApproval {
            get {
                return ResourceManager.GetString("VaccaitionApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation Types.
        /// </summary>
        internal static string VaccationTypes {
            get {
                return ResourceManager.GetString("VaccationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Value is required.
        /// </summary>
        internal static string ValueIsRequired {
            get {
                return ResourceManager.GetString("ValueIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significantly Exceeds Expectations.
        /// </summary>
        internal static string veryExcellent {
            get {
                return ResourceManager.GetString("veryExcellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viudo.
        /// </summary>
        internal static string Viudo {
            get {
                return ResourceManager.GetString("Viudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees awaiting approval.
        /// </summary>
        internal static string WaitingEmployees {
            get {
                return ResourceManager.GetString("WaitingEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Hours.
        /// </summary>
        internal static string WorkHours {
            get {
                return ResourceManager.GetString("WorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Permission.
        /// </summary>
        internal static string WorkingPermission {
            get {
                return ResourceManager.GetString("WorkingPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Shifts.
        /// </summary>
        internal static string WorkShifts {
            get {
                return ResourceManager.GetString("WorkShifts", resourceCulture);
            }
        }
    }
}
