//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Labels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absoluto.
        /// </summary>
        internal static string Absoluto {
            get {
                return ResourceManager.GetString("Absoluto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic &amp; Professional Certificates.
        /// </summary>
        internal static string AcademicCertificates {
            get {
                return ResourceManager.GetString("AcademicCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Education.
        /// </summary>
        internal static string AcademicEducation {
            get {
                return ResourceManager.GetString("AcademicEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Brannch.
        /// </summary>
        internal static string AddBrannch {
            get {
                return ResourceManager.GetString("AddBrannch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Custody.
        /// </summary>
        internal static string AddCustody {
            get {
                return ResourceManager.GetString("AddCustody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Department.
        /// </summary>
        internal static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added By.
        /// </summary>
        internal static string AddedBy {
            get {
                return ResourceManager.GetString("AddedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Job.
        /// </summary>
        internal static string AddJob {
            get {
                return ResourceManager.GetString("AddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Management.
        /// </summary>
        internal static string AddManagement {
            get {
                return ResourceManager.GetString("AddManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add MaterialsConsumption.
        /// </summary>
        internal static string AddMaterialsConsumption {
            get {
                return ResourceManager.GetString("AddMaterialsConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddTask.
        /// </summary>
        internal static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddTraining.
        /// </summary>
        internal static string AddTraining {
            get {
                return ResourceManager.GetString("AddTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vacation.
        /// </summary>
        internal static string AddVacation {
            get {
                return ResourceManager.GetString("AddVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual.
        /// </summary>
        internal static string Annual {
            get {
                return ResourceManager.GetString("Annual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        internal static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Type.
        /// </summary>
        internal static string Blood {
            get {
                return ResourceManager.GetString("Blood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string bod {
            get {
                return ResourceManager.GetString("bod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        internal static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Manager.
        /// </summary>
        internal static string BranchManager {
            get {
                return ResourceManager.GetString("BranchManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancle.
        /// </summary>
        internal static string Cancle {
            get {
                return ResourceManager.GetString("Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        internal static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casado.
        /// </summary>
        internal static string Casado {
            get {
                return ResourceManager.GetString("Casado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO.
        /// </summary>
        internal static string CEO {
            get {
                return ResourceManager.GetString("CEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        internal static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate 1.
        /// </summary>
        internal static string Certificate1 {
            get {
                return ResourceManager.GetString("Certificate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate 2.
        /// </summary>
        internal static string Certificate2 {
            get {
                return ResourceManager.GetString("Certificate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate3.
        /// </summary>
        internal static string Certificate3 {
            get {
                return ResourceManager.GetString("Certificate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil No.
        /// </summary>
        internal static string CivilNo {
            get {
                return ResourceManager.GetString("CivilNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information.
        /// </summary>
        internal static string CompanyInfo {
            get {
                return ResourceManager.GetString("CompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Owner in arabic.
        /// </summary>
        internal static string CompanyOwnerAr {
            get {
                return ResourceManager.GetString("CompanyOwnerAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Owner in english.
        /// </summary>
        internal static string CompanyOwnerEn {
            get {
                return ResourceManager.GetString("CompanyOwnerEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Salary.
        /// </summary>
        internal static string CurrentSalary {
            get {
                return ResourceManager.GetString("CurrentSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custody.
        /// </summary>
        internal static string Custody {
            get {
                return ResourceManager.GetString("Custody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        internal static string DeleteSuccessfully {
            get {
                return ResourceManager.GetString("DeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        internal static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Manager.
        /// </summary>
        internal static string DeptManager {
            get {
                return ResourceManager.GetString("DeptManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Manager Assestant.
        /// </summary>
        internal static string DeptManagerAssestant {
            get {
                return ResourceManager.GetString("DeptManagerAssestant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Supervisor.
        /// </summary>
        internal static string DirectSupervisor {
            get {
                return ResourceManager.GetString("DirectSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Attendance.
        /// </summary>
        internal static string EmployeesAttendance {
            get {
                return ResourceManager.GetString("EmployeesAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Information.
        /// </summary>
        internal static string EmployeesInfo {
            get {
                return ResourceManager.GetString("EmployeesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive Procedures.
        /// </summary>
        internal static string ExecutiveProcedures {
            get {
                return ResourceManager.GetString("ExecutiveProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience 1.
        /// </summary>
        internal static string Experience1 {
            get {
                return ResourceManager.GetString("Experience1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience 2.
        /// </summary>
        internal static string Experience2 {
            get {
                return ResourceManager.GetString("Experience2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience 3.
        /// </summary>
        internal static string Experience3 {
            get {
                return ResourceManager.GetString("Experience3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Passports.
        /// </summary>
        internal static string ExpiredPassports {
            get {
                return ResourceManager.GetString("ExpiredPassports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Manager.
        /// </summary>
        internal static string FinancialManager {
            get {
                return ResourceManager.GetString("FinancialManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Director.
        /// </summary>
        internal static string GeneralDirector {
            get {
                return ResourceManager.GetString("GeneralDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantor.
        /// </summary>
        internal static string Guarantor {
            get {
                return ResourceManager.GetString("Guarantor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head of Department.
        /// </summary>
        internal static string HeadOfDepartment {
            get {
                return ResourceManager.GetString("HeadOfDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment Date.
        /// </summary>
        internal static string HiringDate {
            get {
                return ResourceManager.GetString("HiringDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Manager.
        /// </summary>
        internal static string HRManager {
            get {
                return ResourceManager.GetString("HRManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description.
        /// </summary>
        internal static string JobDescription {
            get {
                return ResourceManager.GetString("JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Details.
        /// </summary>
        internal static string JobDetails {
            get {
                return ResourceManager.GetString("JobDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string JobsTitle {
            get {
                return ResourceManager.GetString("JobsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Manager.
        /// </summary>
        internal static string ManagementManager {
            get {
                return ResourceManager.GetString("ManagementManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to managements.
        /// </summary>
        internal static string Managements {
            get {
                return ResourceManager.GetString("Managements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing Director in arabic.
        /// </summary>
        internal static string ManagingDirectorAr {
            get {
                return ResourceManager.GetString("ManagingDirectorAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing Director in english.
        /// </summary>
        internal static string ManagingDirectorEn {
            get {
                return ResourceManager.GetString("ManagingDirectorEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        internal static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials Consumption.
        /// </summary>
        internal static string MaterialsConsumption {
            get {
                return ResourceManager.GetString("MaterialsConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in Arabic.
        /// </summary>
        internal static string NameAR {
            get {
                return ResourceManager.GetString("NameAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in English.
        /// </summary>
        internal static string NameEN {
            get {
                return ResourceManager.GetString("NameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Employee.
        /// </summary>
        internal static string NewEmployee {
            get {
                return ResourceManager.GetString("NewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offices.
        /// </summary>
        internal static string Offices {
            get {
                return ResourceManager.GetString("Offices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport End Date.
        /// </summary>
        internal static string PassportEnddate {
            get {
                return ResourceManager.GetString("PassportEnddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport And residence .
        /// </summary>
        internal static string PassportInfo {
            get {
                return ResourceManager.GetString("PassportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passport No.
        /// </summary>
        internal static string passportNo {
            get {
                return ResourceManager.GetString("passportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Start Date.
        /// </summary>
        internal static string PassportStartdate {
            get {
                return ResourceManager.GetString("PassportStartdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Manager in arabic.
        /// </summary>
        internal static string PersonnelManagerAr {
            get {
                return ResourceManager.GetString("PersonnelManagerAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Manager in english.
        /// </summary>
        internal static string PersonnelManagerEn {
            get {
                return ResourceManager.GetString("PersonnelManagerEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical.
        /// </summary>
        internal static string Physical {
            get {
                return ResourceManager.GetString("Physical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Employment.
        /// </summary>
        internal static string PreviousEmployment {
            get {
                return ResourceManager.GetString("PreviousEmployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Experience.
        /// </summary>
        internal static string PreviousExperience {
            get {
                return ResourceManager.GetString("PreviousExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        internal static string Recovery {
            get {
                return ResourceManager.GetString("Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated Every.
        /// </summary>
        internal static string RepeatedEvery {
            get {
                return ResourceManager.GetString("RepeatedEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        internal static string SaveSuccessfully {
            get {
                return ResourceManager.GetString("SaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Num.
        /// </summary>
        internal static string SequenceNum {
            get {
                return ResourceManager.GetString("SequenceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soltero.
        /// </summary>
        internal static string Soltero {
            get {
                return ResourceManager.GetString("Soltero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string TextDirection {
            get {
                return ResourceManager.GetString("TextDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TheName {
            get {
                return ResourceManager.GetString("TheName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        internal static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainings.
        /// </summary>
        internal static string Trainings {
            get {
                return ResourceManager.GetString("Trainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unified Number.
        /// </summary>
        internal static string UnifiedNumber {
            get {
                return ResourceManager.GetString("UnifiedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Information.
        /// </summary>
        internal static string UsersInfo {
            get {
                return ResourceManager.GetString("UsersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation.
        /// </summary>
        internal static string Vacation {
            get {
                return ResourceManager.GetString("Vacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacations.
        /// </summary>
        internal static string Vacations {
            get {
                return ResourceManager.GetString("Vacations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacations Balance.
        /// </summary>
        internal static string VacationsBalance {
            get {
                return ResourceManager.GetString("VacationsBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacaition Approval.
        /// </summary>
        internal static string VaccaitionApproval {
            get {
                return ResourceManager.GetString("VaccaitionApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation Types.
        /// </summary>
        internal static string VaccationTypes {
            get {
                return ResourceManager.GetString("VaccationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viudo.
        /// </summary>
        internal static string Viudo {
            get {
                return ResourceManager.GetString("Viudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees awaiting approval.
        /// </summary>
        internal static string WaitingEmployees {
            get {
                return ResourceManager.GetString("WaitingEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Hours.
        /// </summary>
        internal static string WorkHours {
            get {
                return ResourceManager.GetString("WorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Permission.
        /// </summary>
        internal static string WorkingPermission {
            get {
                return ResourceManager.GetString("WorkingPermission", resourceCulture);
            }
        }
    }
}
