//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resource
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentCategories()
        {
            this.DocumentCategories1 = new HashSet<DocumentCategories>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryCode { get; set; }
        public string NameAR { get; set; }
        public string NameEN { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> IsFixed { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> CreateUserID { get; set; }
        public Nullable<long> UpdateUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentCategories> DocumentCategories1 { get; set; }
        public virtual DocumentCategories DocumentCategories2 { get; set; }
        public virtual employees employees { get; set; }
        public virtual employees employees1 { get; set; }
    }
}
