//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resource
{
    using System;
    using System.Collections.Generic;
    
    public partial class evaluations
    {
        public int EvaluationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> ReviewerID { get; set; }
        public Nullable<System.DateTime> EvaluationDate { get; set; }
        public string Behavior { get; set; }
        public string Attendance { get; set; }
        public string Punctuality { get; set; }
        public string Productivity { get; set; }
        public string Creativity { get; set; }
        public string ClientRelation { get; set; }
        public string Initiative { get; set; }
        public string Communication { get; set; }
        public string Cooperation { get; set; }
        public string StrategicThinking { get; set; }
        public string HandleStressful { get; set; }
        public string ListeningSkills { get; set; }
        public string MeetingDeadlines { get; set; }
        public string Performance { get; set; }
        public string JobKnowledge { get; set; }
        public string OrganizeIdea { get; set; }
        public string RespondResourcefully { get; set; }
        public string ConfrontsProblems { get; set; }
        public string CustomerNeeds { get; set; }
        public string OrganizationVision { get; set; }
        public string StayFocused { get; set; }
        public string OverAllProgress { get; set; }
        public string Comment { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual employees employees { get; set; }
        public virtual employees employees1 { get; set; }
    }
}
