//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resource
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheduledJobs
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
    }
}
