//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resource
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRSystemEntities : DbContext
    {
        public HRSystemEntities()
            : base("name=HRSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<companies> companies { get; set; }
        public DbSet<confirms> confirms { get; set; }
        public DbSet<custodies> custodies { get; set; }
        public DbSet<departments> departments { get; set; }
        public DbSet<employees> employees { get; set; }
        public DbSet<employeesScheduleVacations> employeesScheduleVacations { get; set; }
        public DbSet<employeesTrainings> employeesTrainings { get; set; }
        public DbSet<employeesVacations> employeesVacations { get; set; }
        public DbSet<hourlyPermissions> hourlyPermissions { get; set; }
        public DbSet<Images> Images { get; set; }
        public DbSet<jobs> jobs { get; set; }
        public DbSet<materialsConsumption> materialsConsumption { get; set; }
        public DbSet<messages> messages { get; set; }
        public DbSet<messagesTemplates> messagesTemplates { get; set; }
        public DbSet<offices> offices { get; set; }
        public DbSet<periods> periods { get; set; }
        public DbSet<rewards> rewards { get; set; }
        public DbSet<salaryIncrease> salaryIncrease { get; set; }
        public DbSet<scheduleVacations> scheduleVacations { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tasks> tasks { get; set; }
        public DbSet<trainings> trainings { get; set; }
        public DbSet<userCardSettings> userCardSettings { get; set; }
        public DbSet<vacations> vacations { get; set; }
        public DbSet<employeesTasks> employeesTasks { get; set; }
    }
}
