//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resource
{
    using System;
    using System.Collections.Generic;
    
    public partial class salaryIncrease
    {
        public salaryIncrease()
        {
            this.confirms = new HashSet<confirms>();
        }
    
        public int SalaryIncreaseID { get; set; }
        public string Name { get; set; }
        public string IncreaseType { get; set; }
        public Nullable<decimal> IncreaseValue { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<confirms> confirms { get; set; }
    }
}
